openapi: 3.0.0
info:
  title: Authoriz
  version: '1.0'
  description: Used to authorize requests
servers:
  - url: 'http://localhost:3000'
paths:
  /api/rule:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-validate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuleRequest'
        description: ''
    parameters: []
    post:
      summary: ''
      operationId: post-api-rule
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    delete:
      summary: ''
      operationId: delete-api-rule
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    ValidateRule:
      title: ValidateRule
      type: object
      x-examples:
        example-1:
          subject: '198419464'
          tenant: Tenant-19202
          resource: exampleService
          action: read
      properties:
        subject:
          type: string
        tenant:
          type: string
        resource:
          type: string
        action:
          type: string
      description: Validates a rule
