openapi: 3.0.0
info:
  title: Authoriz
  version: '1.0'
  description: Used to authorize requests
servers:
  - url: 'http://localhost:3000'
paths:
  /api/policy:
    get:
      summary: Validates a policy
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-api-validate
      parameters:
        - schema:
            type: string
          in: query
          name: sub
        - schema:
            type: string
          in: query
          name: ten
        - schema:
            type: string
          in: query
          name: res
        - schema:
            type: string
          in: query
          name: act
      description: ''
    parameters: []
    put:
      summary: Creates a new policy
      operationId: put-api-rule
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRule'
        description: ''
      security:
        - jwtAuth: []
    delete:
      summary: Delete a policy
      operationId: delete-api-rule
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRule'
      security:
        - jwtAuth: []
components:
  schemas:
    ValidateRule:
      title: ValidateRule
      type: object
      x-examples:
        example-1:
          subject: '198419464'
          tenant: Tenant-19202
          resource: exampleService
          action: read
      properties:
        subject:
          type: string
        tenant:
          type: string
        resource:
          type: string
        action:
          type: string
      description: Validates a rule
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
