openapi: 3.0.0
info:
  title: Authoriz
  version: '1.0'
  description: Used to authorize requests
servers:
  - url: 'http://localhost:3000'
paths:
  /api/rule:
    get:
      summary: Validates a API rule
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-validate
      parameters:
        - schema:
            type: string
          in: query
          name: sub
        - schema:
            type: string
          in: query
          name: ten
        - schema:
            type: string
          in: query
          name: res
        - schema:
            type: string
          in: query
          name: act
      description: ''
    parameters: []
  /api/management/rule:
    put:
      summary: ''
      operationId: put-api-management-rule
      responses:
        '200':
          description: OK
components:
  schemas:
    ValidateRule:
      title: ValidateRule
      type: object
      x-examples:
        example-1:
          subject: '198419464'
          tenant: Tenant-19202
          resource: exampleService
          action: read
      properties:
        subject:
          type: string
        tenant:
          type: string
        resource:
          type: string
        action:
          type: string
      description: Validates a rule
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
