openapi: 3.0.0
info:
  title: Authoriz
  version: '1.0'
  description: Used to authorize requests
servers:
  - url: 'http://localhost:3000'
paths:
  /api/policy:
    parameters: []
    put:
      summary: Creates a new policy
      operationId: put-api-rule
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRule'
        description: ''
      security:
        - jwtAuth: []
    delete:
      summary: Delete a policy
      operationId: delete-api-rule
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRule'
      security:
        - jwtAuth: []
  /api/policy/group:
    put:
      summary: ''
      operationId: put-api-policy-group
      responses:
        '201':
          description: Created
      security:
        - jwtAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                tenant:
                  type: string
    get:
      summary: ''
      operationId: get-api-policy-group
      responses:
        '200':
          description: OK
  /api/validate:
    post:
      summary: ''
      operationId: post-api-validate
      responses:
        '200':
          description: OK
components:
  schemas:
    ValidateRule:
      title: ValidateRule
      type: object
      x-examples:
        example-1:
          subject: '198419464'
          tenant: Tenant-19202
          resource: exampleService
          action: read
      properties:
        subject:
          type: string
        tenant:
          type: string
        resource:
          type: string
        action:
          type: string
      description: Validates a rule
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
